name: salmon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.2
  dash_flags: ^0.1.1
  file_picker: ^5.3.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_bounceable: ^1.1.0
  flutter_hooks: ^0.18.6
  flutter_local_notifications: ^15.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone_updated_gradle: ^2.0.3
  font_awesome_flutter: ^10.5.0
  get_storage: ^2.1.1
  go_router: ^5.2.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.3.1
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.0
  intl: any
  logger: ^1.4.0
  lottie: ^2.4.0
  riverpod_annotation: ^2.1.1
  search_page: ^2.3.0
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2
  uuid: ^3.0.7
  validators: ^3.0.0
  wave: ^0.2.2
  webview_flutter: ^4.2.2
  stream_chat_flutter: ^6.4.0 
  flutter_dotenv: ^5.1.0
  liquid_swipe: ^3.1.0
  we_slide: ^2.4.0
  detectable_text_field: ^2.1.0
  mime: ^1.0.4
  video_player: ^2.7.0
  easy_stepper: ^0.7.3
  lazy_load_indexed_stack: ^1.0.1
  photo_manager: ^2.7.0
  flutter_markdown: ^0.6.17+1
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.63.0
  animated_flip_counter: ^0.2.6
  collection: ^1.17.1
  concentric_transition: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3

dependency_overrides:
  http: ^0.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/anims/
    - .env